# Generated by Django 5.2 on 2025-04-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='uploads/subject_icon')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
