# Generated by Django 5.2 on 2025-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indexbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='fav_icon',
            field=models.ImageField(default=1, upload_to='uploads/fav_icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='header_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
