# Generated by Django 5.2 on 2025-04-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery_item')),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem')),
            ],
        ),
    ]
